server:
  port: 8082

spring:
  application:
    name: banking-onboarding-api

  datasource:
    url: jdbc:postgresql://localhost:5432/banking_db
    username: ${DB_USERNAME:banking_user}
    password: ${DB_PASSWORD:SecureBankingPass123!}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/banking}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/banking/protocol/openid-connect/certs}

# Keycloak admin client only needed for user registration
keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:banking}
  resource: ${KEYCLOAK_CLIENT_ID:banking-service-api}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:PH0hqqtK2gAO8pxtCKu6q+aOQre3ANUcmFDjpUyMDwE=}
  admin:
    username: ${KEYCLOAK_ADMIN_USER:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

customer:
  service:
    url: ${CUSTOMER_SERVICE_URL:http://localhost:9080/}
    max-buffer-size: ${CUSTOMER_SERVICE_MAXBUFFERSIZE:500000}

rteller:
  service:
    url: ${RTELLER_SERVICE_URL:http://localhost:9081/}

account:
  service:
    url: ${ACCOUNT_SERVICE_URL:http://localhost:9082/}

account-stats:
  service:
    url: ${ACCOUNT_STATS_SERVICE_URL:http://localhost:9083/}

account-fin:
  service:
    url: ${ACCOUNT_FIN_SERVICE_URL:http://localhost:9085/}

de:
  service:
    url: ${DE_SERVICE_URL:http://localhost:9086/}

bst:
  service:
    url: ${BST_SERVICE_URL:http://localhost:9087/}

image:
  service:
    url: ${IMAGE_SERVICE_URL:http://localhost:9088/}

account-class:
  service:
    url: ${ACCOUNT_CLASS_SERVICE_URL:http://localhost:9089/}

springdoc:
  swagger-ui:
    oauth:
      client-id: banking-swagger
      use-pkce-with-authorization-code-grant: true

logging:
  level:
    org:
      springframework:
        security=DEBUG: